# goreleaser.yml
build:
  binary: links
  goos:
    - windows
    - linux
    - freebsd
  goarch:
    - amd64
    - 386
  ldflags: -s -w -X main.version=v{{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
archive:
  format_overrides:
    - goos: windows
      format: zip
release:
  draft: true
snapshot:
  name_template: snapshot-{{.Commit}}
snapcraft:
  name: linksml
  summary: URL Shortener
  description: Simple, fast link shortener
  apps:
    links:
      plugs: [network, network-bind, home]
